service: pastebin

frameworkVersion: '>=3.0.0'

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  region: eu-west-2

custom:
  go:
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true
    cmd: CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -tags lambda.norpc -ldflags="-s -w"
  betterCredentials:
    enabled: true

plugins:
  - serverless-better-credentials
  - serverless-go-plugin

functions:
  example:
    handler: ./functions/example/main.go # or just "./functions/example"
    events:
      - httpApi: 'GET /example'

resources:
  Resources:
    IncomingBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${aws:accountId}-${sls:stage}-pastebin-incoming
        VersioningConfiguration:
          Status: Enabled
