service: example-service

frameworkVersion: '>=3.0.0'

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  region: eu-west-2

custom:
  go:
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true
  betterCredentials:
    enabled: true


plugins:
  - serverless-better-credentials
  - serverless-go-plugin

functions:
  example:
    handler: ./functions/example/main.go # or just "./functions/example"